# Включаем скрытые файлы
include:
  - .well-known

# Исключаем файлы iOS проекта
exclude:
  - "*.xcodeproj"
  - "*.xcworkspace"
  - "*.swift"
  - "Podfile*"
  - "*.md"
  - "Pods/"

# Настройки Jekyll
plugins:
  - jekyll-sitemap

# Настройки для AASA файла
defaults:
  - scope:
      path: ".well-known/apple-app-site-association"
    values:
      layout: null
      content_type: "application/json"

# Отключаем обработку для .well-known
keep_files:
  - .well-known
