include:
  - apple-app-site-association
  - .well-known

plugins:
  - jekyll-optional-front-matter

defaults:
  - scope:
      path: "apple-app-site-association"
    values:
      content-type: "application/json"
